name = "api"
compatibility_date = "2023-12-01"

[vars]
PUIBLIC_JWK_CACHE_KEY = "public-jwk-cache-key"

[[kv_namespaces]]
binding = "PUBLIC_JWK_CACHE_KV"
id = "0b579dc3093b450eb98f5af4e68700f0"
preview_id = "38871d44f68846249546a435f7ea274f"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "userinfo"
database_id = "b4e12f55-3aff-4181-aa0a-df564de50014"
